### ISSUE TITLE
Example for Kotlin usage?

### ISSUE THREAD

**Issue by DavidBerdik** [PacifistMC/pacifist-remapper#1]
Do you have an example of how to use this plugin with Kotlin-based Gradle files? I am trying to set it up for my project, but I have not been able to do so.

**Comment by DavidBerdik** [comment]
I've managed to migrate (https://bitbucket.org/David-B/herobrine-2/commits/821f546fd7876ddce807635c81c5f6a3a1199700), but I am still having issues when I try to compile and run my plugin.

I get this stack trace in the server log:
```
java.lang.NoSuchFieldError: MONSTER
        at net.theprogrammersworld.herobrine.Herobrine.onEnable(Herobrine.java:94) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:521) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:435) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

Do you have any advice for how to resolve it? What am I doing wrong?

**Comment by DavidBerdik** [comment]
It looks like there's an issue with Enums not remapping properly. If I try to comment out the part that breaks in the above code, this happens:

```
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:613) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchFieldError: SERVERBOUND
        at net.theprogrammersworld.herobrine.NPC.Network.NetworkCore.<init>(NetworkCore.java:9) ~[?:?]
        at net.theprogrammersworld.herobrine.NPC.NPCCore.<init>(NPCCore.java:55) ~[?:?]
        at net.theprogrammersworld.herobrine.Herobrine.onServerLoad(Herobrine.java:108) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

**Comment by Ran-Mewo** [comment]
Oops github didn't notify me about this issue _and that I was working on 1.18.2 update_
anyways the latest version should fix the enum issue


Though since you aren't using mixins I recommend using SpecialSource to remap
there's this plugin for it
https://github.com/patrick-choe/mojang-spigot-remapper

**Comment by DavidBerdik** [comment]
That's alright! The plugin that you are directing me to is actually what I ended up using after an unsuccessful attempt with yours. Out of curiosity though, what are mixins? I've never heard that term before.

**Comment by Ran-Mewo** [comment]
Basically you can modify the code of minecraft using mixins
https://github.com/SpongePowered/Mixin

**Comment by DavidBerdik** [comment]
Very useful. Thank you for sharing!
